# Generated by Django 4.1.7 on 2023-03-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
