# Generated by Django 4.1.7 on 2023-03-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='file',
            field=models.CharField(default='smile.jpg', max_length=200),
        ),
    ]
