# Generated by Django 4.1.7 on 2023-03-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_art_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='type',
            field=models.CharField(default='drawing', max_length=50),
        ),
    ]
